# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: sbitton/jb_devops_final:v-45
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 45
  name: "ec2report"
deployment:
  name: "workapp"
  namespace: "argocd"
  lables:
    app: workapp
service:
  name: "svcec3r"
  type: NodePort
  port: 8081
